# Generated by Django 2.2.4 on 2019-09-22 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('work_author', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='')),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('FT', 'Fairy Tale'), ('BA', 'Biography-Autobiography'), ('CL', 'Classic'), ('RO', 'Romance'), ('AA', 'Action and Adventure'), ('CD', 'Crime and Detective'), ('CN', 'Comic and Graphic Novel'), ('HI', 'Historical Fiction'), ('MY', 'Mythology'), ('ST', 'Suspense-Thriller'), ('SF', 'Science Fiction'), ('F', 'Fantasy'), ('P', 'Poetry'), ('S', 'Satire'), ('E', 'Essay')], max_length=2)),
                ('sticker', models.CharField(blank=True, choices=[('P', 'primary'), ('Se', 'secondary'), ('S', 'success'), ('D', 'danger'), ('I', 'info'), ('W', 'warning'), ('DE', 'default')], max_length=2, null=True)),
                ('slug', models.SlugField()),
                ('publish_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('bestseller', models.BooleanField(default=False)),
                ('notbestseller', models.BooleanField(default=False)),
                ('longbook', models.BooleanField(default=False)),
                ('shortbook', models.BooleanField(default=False)),
                ('worldwide_appreciated', models.BooleanField(default=False)),
                ('underground_appreciation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaveCustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('house_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.SaveCustomerAddress')),
                ('items', models.ManyToManyField(to='book.OrderItem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
