# Generated by Django 2.2.4 on 2019-08-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190830_1144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Book',
        ),
    ]
