# Generated by Django 2.2.4 on 2019-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190830_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sticker',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('S', 'success'), ('D', 'danger'), ('W', 'warning'), ('I', 'info'), ('L', 'light'), ('D', 'dark')], max_length=2),
        ),
    ]
