# Generated by Django 2.2.4 on 2019-08-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190831_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='default_book'),
            preserve_default=False,
        ),
    ]
