# Generated by Django 2.2.4 on 2019-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
