# Generated by Django 2.2.4 on 2019-09-01 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0015_auto_20190902_0043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='SaveCustomerAddress',
        ),
    ]
