# Generated by Django 2.2.4 on 2019-09-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20190902_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savecustomeraddress',
            old_name='apartment_address',
            new_name='street_address',
        ),
    ]
