# Generated by Django 2.2.4 on 2019-09-05 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_remove_savecustomeraddress_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='longbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='notbestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='shortbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='underground_appreciation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='worldwide_appreciated',
            field=models.BooleanField(default=False),
        ),
    ]
