# Generated by Django 2.2.4 on 2019-09-05 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20190905_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='work_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
