# Generated by Django 2.2.4 on 2019-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
