# Generated by Django 2.2.4 on 2019-09-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190831_2113'),
        ('book', '0021_book_publish_date'),
        ('book', '0022_book_cover'),
    ]

    operations = [
    ]
