# Generated by Django 2.2.4 on 2019-09-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20190907_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
