# Generated by Django 2.2.4 on 2019-09-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0027_author_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='work_author',
        ),
    ]
