# Generated by Django 2.2.4 on 2019-09-08 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0028_remove_book_work_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='work_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
