# Generated by Django 2.2.4 on 2019-09-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_auto_20190904_1303'),
        ('book', '0029_auto_20190908_1750'),
        ('book', '0011_auto_20190831_2113'),
    ]

    operations = [
    ]
