# Generated by Django 2.2.4 on 2019-09-16 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_merge_20190915_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FT', 'Fairy Tale'), ('BA', 'Biography-Autobiography'), ('CL', 'Classic'), ('RO', 'Romance'), ('AA', 'Action and Adventure'), ('CD', 'Crime and Detective'), ('CN', 'Comic and Graphic Novel'), ('HI', 'Historical Fiction'), ('MY', 'Mythology'), ('ST', 'Suspense-Thriller'), ('SF', 'Science Fiction'), ('F', 'Fantasy'), ('P', 'Poetry'), ('S', 'Satire'), ('E', 'Essay')], max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='sticker',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('Se', 'secondary'), ('S', 'success'), ('D', 'danger'), ('I', 'info'), ('W', 'warning'), ('DE', 'default')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
